=== kwilcox/ncWMS/src/java/ncWMSconfig.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.resc.rdg.ac.uk/"
    xmlns="http://www.resc.rdg.ac.uk/"
    elementFormDefault="qualified">

<xs:element name="ncWMS">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="service">
            <xs:complexType>
                <xs:all>
                    <xs:element name="title" type="xs:string"/>
                    <xs:element name="fees" type="xs:string" default="none"/>
                    <xs:element name="accessConstraints" type="xs:string" minOccurs="0" maxOccurs="1" default="none"/>
                    <!-- Can only currently handle 1 layer at a time -->
                    <xs:element name="layerLimit" fixed="1">
                        <xs:simpleType>
                          <xs:restriction base="xs:positiveInteger">
                            <xs:minInclusive value="1"/>
                          </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="maxWidth" default="1000">
                        <xs:simpleType>
                          <xs:restriction base="xs:positiveInteger">
                            <xs:minInclusive value="1"/>
                          </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="maxHeight" default="1000">
                        <xs:simpleType>
                          <xs:restriction base="xs:positiveInteger">
                            <xs:minInclusive value="1"/>
                          </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="href" type="xs:string"/>
                </xs:all>
            </xs:complexType>
        </xs:element>
        <xs:element name="datasets">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="dataset" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="id" type="xs:ID" use="required"/>
                            <xs:attribute name="title" type="xs:string" use="required"/>
                            <xs:attribute name="location" type="xs:string" use="required"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== kwilcox/ncWMS/src/java/ncWMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : ncWMS.xml
    Created on : 30 September 2006, 11:35
    Author     : Jon
    Description:
        Configuration file for the Web Map Service
-->

<ncWMS xmlns="http://www.resc.rdg.ac.uk/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.resc.rdg.ac.uk/ ncWMSconfig.xsd">
    <service>
        <name>ncWMS</name>
        <title>NetCDF Web Map Service</title>
        <href>http://www.nerc-essc.ac.uk</href>
        <!-- The elements below all have default values and so can be left empty.
             However, they must be present in the configuration file. -->
        <fees></fees>
        <accessConstraints></accessConstraints>
        <layerLimit></layerLimit>
        <maxWidth></maxWidth>
        <maxHeight></maxHeight>
    </service>
    <datasets>
        <!--<dataset id="Ifremer" title="Test Ifremer dataset" location="C:\data\OA_20060830.nc"/>
        <dataset id="FOAM" title="Test aggregated dataset" location="C:\data\FOAM_one.ncml"/>-->
        <!--<dataset id="FOAM9" title="Test rotated dataset" location="L:\data\cadfael1\marine\FOAM\MERSEA\FOAM_ATL19_ANAL_CLASS1_GRIB_20060616.nc"/>-->
        <!--<dataset id="CORIOLIS" title="CORIOLIS via OPeNDAP" location="http://www.ifremer.fr/thredds/dodsC/global/weekly/temperature/CORT-GLOBAL-01"/>-->
        <!--<dataset id="CERSAT" title="CERSAT data via OPeNDAP" location="http://www.ifremer.fr/thredds/dodsC/sst/cms/daily"/>-->
        <dataset id="MRCS" title="POLCOMS MRCS data" location="C:\data\POLCOMS_MRCS_NOWCAST_20060731.nc"/>
        <dataset id="FOAM" title="NCOF FOAM data" location="C:\data\FOAM_20050422.0.nc"/>
    </datasets>
</ncWMS>
